### ISSUE TITLE
Bell ring resets display view

### ISSUE THREAD

**Issue by olimexsmart** [bstnfrmry/hanabi#214] opened 2020-12-17 10:51 UTC
If when is your turn one of the players rings the your bell, the expanded view of your card is collapsed. 

This is particularly annoying when just about to make a move and the view continues to collapse because the other players don't stop ringing for a second

**Comment by bstnfrmry** [comment] 2020-12-17 12:00
Thanks for the feedback! We're very familiar with this annoying as hell bug 😁 

Closing as duplicate of https://github.com/bstnfrmry/hanabi/issues/163

**Closed by bstnfrmry** 2020-12-17 12:00 UTC
